# APP
spring.application.name=StrongMemoryAPI

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# LOGS
logging.file.name=logs/app.log
server.error.include-message=always

# ENCODING
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.mvc.converters.preferred-json-mapper=jackson

# ACTUATOR
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never