spring.application.name=StrongMemoryAPI

# Driver:
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Credentials and URL:
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.hikari.initializationFailTimeout=60000
spring.datasource.hikari.connectionTimeout=60000

# JPA e Hibernate:
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

#JWT:
jwt.secret=Jwt&Secret&Key&Strong&Memory&Application&123&Acb
jwt.expiration-ms=3600000

#LOGS
logging.file.name=logs/app.log
server.error.include-message=always
server.error.include-stacktrace=always

# CACHE:
# spring.cache.type=
# spring.redis.host=${SPRING_REDIS_HOST}
# spring.redis.port=${SPRING_REDIS_PORT}

# ENCODING
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.mvc.converters.preferred-json-mapper=jackson
